print("hello world")
print("hello my name is Jack")
print("What is your name")
name = input("name:")
print("How old are you")
age = input("age: ")
print("Hello" + name)
print("How are you doing" + name)
response = input("response")
